In [26]:
list1=[5,8,9,7]
list2=[6,7,3,2]


In [27]:
import numpy as np

In [28]:
arr1=np.array(list1)
arr2=np.array(list2)


In [29]:
arr1+arr2

array([11, 15, 12,  9])

In [30]:
arr1.dtype

dtype('int32')

In [31]:
np.array([1,2,3,'4','x'])


array(['1', '2', '3', '4', 'x'], dtype='<U11')

In [32]:
arr2= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr2.ndim

2

In [35]:
arr2.ndim

2

arr2.shape

arr2.shape

In [36]:
arr2.shape

(3, 3)

In [37]:
arr2.dtype

dtype('int32')

In [45]:
arr3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
arr3 = np.arange(4,20)

In [46]:
arr4=arr3.reshape(4,4)

In [47]:
arr4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
arr3[5]

9

In [49]:
arr4[2]

array([12, 13, 14, 15])

In [50]:
arr4[0:2]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
arr4[3:2]

array([], shape=(0, 4), dtype=int32)

In [52]:
arr4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [53]:
arr4[:,2]

array([ 6, 10, 14, 18])

In [54]:
arr4[1,2] =100

In [55]:
arr4

array([[  4,   5,   6,   7],
       [  8,   9, 100,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19]])

In [57]:
arr5=np.array([[5,6,9],[-8,7,2],[-1,4,5]])

In [58]:
arr5

array([[ 5,  6,  9],
       [-8,  7,  2],
       [-1,  4,  5]])

In [60]:
arr5.sum()

29

In [62]:
arr5.mean()

3.2222222222222223

In [63]:
np.median(arr5)

5.0

In [65]:
arr5+5

array([[10, 11, 14],
       [-3, 12,  7],
       [ 4,  9, 10]])

In [67]:
arr5*100


array([[ 500,  600,  900],
       [-800,  700,  200],
       [-100,  400,  500]])

In [68]:
arr6=arr5*100

In [71]:
arr6=[[10,20,30,40],[80,90,60,50],[40,30,20,10]]

In [72]:
np.sqrt(arr6) 

array([[3.16227766, 4.47213595, 5.47722558, 6.32455532],
       [8.94427191, 9.48683298, 7.74596669, 7.07106781],
       [6.32455532, 5.47722558, 4.47213595, 3.16227766]])

# Special Arrays

In [73]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [74]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])